name: communicator
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  introduction_screen: ^3.1.4
  google_fonts: ^4.0.1
  page_transition: ^2.0.9
  flutter_event_calendar: ^1.0.0
  font_awesome_flutter: ^10.3.0
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  shared_preferences: ^2.0.17
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.1.0
  flutter_localizations:
    sdk: flutter
  dotted_border: ^2.0.0+3
  image_picker: ^0.8.6+1
  firebase_storage: ^11.0.10
  flutter_launcher_icons: ^0.11.0
  flutter_screenutil: ^5.6.1
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  
  assets:
     - assets/images/
     - assets/images/emotions/
     - assets/json/


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 
